
template: Hi, %s is Learning Java

defaultName: Stranger

logging:
  level: INFO
  loggers:
    com.quovantis: DEBUG

server:
  type: simple
  connector:
    type: http
    port: 8080

database:
  # the name of your JDBC driver
  driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # the username
  user: sa

  # the password
  password: anshul.123

  # the JDBC URL
  url: jdbc:sqlserver://localhost;databaseName=JAVA_LEARNING;